---
- name: Ansible SSL Helper - Create CA
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Set user inputs as facts
      ansible.builtin.set_fact:
        ash_ca_key_passphrase: "{{ ca_key_passphrase | default('', true) }}"
        ash_ca_key_path: "{{ ca_key_path | default('~/ca_cert.key', true) }}"
        ash_ca_cert_path: "{{ ca_cert_path | default('~/ca_cert.pem', true) }}"
        ash_ca_common_name: "{{ ca_cn | default('Self Signed CA', true) }}"

    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        path: "{{ ash_ca_key_path }}"
        passphrase: "{{ ash_ca_key_passphrase }}"
        cipher: auto

    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ ash_ca_key_path }}"
        privatekey_passphrase: "{{ ash_ca_key_passphrase }}"
        common_name: "{{ ash_ca_common_name }}"
        use_common_name_for_san: false
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: _ca_csr

    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ ash_ca_cert_path }}"
        csr_content: "{{ _ca_csr.csr }}"
        privatekey_path: "{{ ash_ca_key_path }}"
        privatekey_passphrase: "{{ ash_ca_key_passphrase }}"
        provider: selfsigned
